obstacle_range: 30.0
raytrace_range: 15.0
footprint: [[-0.51, 0.42], [0.51, 0.42], [0.51, -0.42], [-0.50, -0.42]]
inflation_radius: 0.55

transform_tolerance: 0.2 # Max running just hardware nodes is ~0.0006 secs according to tf_monitor

observation_sources: hokuyo_laser_scan_sensor
# observation_sources: laser_scan_sensor point_cloud_sensor

hokuyo_laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan_filtered, 
                           marking: true, clearing: true,  expected_update_rate: 0.04} # LRF @ 25Hz
# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}